version: "3"
services:
    neo4j:
        build:
            context: .
            dockerfile: Dockerfile.neo4j.dev
        ports:
            - 7474:7474
            - 7687:7687
        env_file: ./neo4j-dev.env
